server:
  port: 80

spring:
  application:
    name: cloud-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #采样率值介于0到1之间，则表示全部采集

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册EurekaServer，默认为true
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #集群版
      defaultZone: http://eureka7001.com:7001/eureka/ #单机版
  instance:
    instance-id: order80
    prefer-ip-address: true #访问路径显示IP地址