server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #配置Nacos地址

#自定义
service-url: #消费者将要访问的微服务名称（注册成功进Nacos的服务提供者）
  nacos-user-service: http://nacos-payment-provider


