server:
  port: 80

spring:
  application:
    name: feign-hystrix-consumer-order

eureka:
  client:
    register-with-eureka: true #表示是否将自己注册EurekaServer，默认为true
    fetchRegistry: true #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true，才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: hystrix-order80
    prefer-ip-address: true #访问路径显示IP地址

feign:
  hystrix:
    enabled: true #如果处理自身的容错就开启。开启方式与生产端不一样。